### ISSUE TITLE
Logging error at the end of binstar-build tail -f 

### ISSUE THREAD

**Issue by asmeurer** [Anaconda-Server/anaconda-build#22] opened 2014-12-11 21:01 UTC
```
[Test]
cd tests\test-recipes\metadata
for /D %f in (*) do (C:\Users\binstar\conda-build-miniconda\conda-build --no-binstar-upload %~nf)
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\binstar\conda-build-miniconda\conda-build' is not recognized as an internal or external command,
operable program or batch file.
Exit BINSTAR_BUILD_RESULT=failure

Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/envs/binstar-build/lib/python2.7/logging/handlers.py", line 861, in emit
    self.socket.send(msg)
error: [Errno 40] Message too long
Logged from file info.py, line 46
[error] Build Failed
```

This is from `binstar-build tail conda/conda-build 29.0 -f` (https://binstar.org/conda/conda-build/builds/29/0)

**Comment by srossross** [comment] 2015-10-14 17:54
duplicate of #27

**Closed by srossross** 2015-10-14 17:54 UTC
Labels: bug, Component - Build
