### ISSUE TITLE
Probably somehow broken 'unregister' feature - invalid status on web page interface

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/anaconda-build#50] opened 2015-06-11 19:37 UTC
_From @mutirri on June 10, 2015 14:9_

We have one `win32` machine with `build-worker` (as far as I know).
On this machine was just one running binstar process: `binstar-build.exe`.

However on the page: https://binstar.org/organization/binstar/settings/build-queue
I saw two available workers.
Maybe `chalmers restart -a` command didn't properly perform `unregister` action.
Or maybe refresh time is too small.

_Copied from original issue: Anaconda-Server/binstar-build-worker#9_

**Comment by srossross** [comment] 2015-10-14 17:51
Is this fixed by #89?

**Comment by PeterDSteinberg** [comment] 2015-10-15 16:04
@srossross I think the issue is likely fixed by #89, but I don't have a Windows machine to test.
@malev Could you check to see if the settings/build-queue page makes sense  when you are running windows workers today?  The page should show registered workers on each queue and that should be in agreement with the worker_id you have registered.

**Comment by malev** [comment] 2015-10-19 20:44
@PeterDSteinberg @srossross I can only see one windows registered so I believe this is ready to be closed. Opinions?

**Closed** 2015-10-19 21:55 UTC
Labels: bug, Component - Build
