### ISSUE TITLE
Placeholder: A-Sever #1702 - Provide more information on build queue depth for each platform

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-build#249] opened 2016-03-18 18:00 UTC
Actual code and progress should be tracked over here, but just so we can have consolidated view in the build repo: 

anaconda-server/anaconda-server#1702

**Comment by kalefranz** [comment] 2016-03-21 18:23
Duplicate of #207

**Closed by kalefranz** 2016-03-21 18:23 UTC
