### ISSUE TITLE
binstar upload missing argument

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#100] opened 2015-10-13 22:10 UTC
There is sometimes a missing channel argument to ```binstar upload```.  Also ```binstar upload``` should be changed to ```anaconda upload```, I think.
```bash
1534[Build Targets]
1535binstar -q -t $TOKEN upload --force --user anaconda-cluster --package anaconda-cluster  --channel  /home/binstar/miniconda/conda-bld/linux-64/*.tar.bz2 --build-id 1087.0
1536usage: binstar upload [-h] [-c CHANNELS] [--no-progress] [-u USER]
1537                      [-p PACKAGE] [-v VERSION] [-s SUMMARY] [-t PACKAGE_TYPE]
1538                      [-d DESCRIPTION] [--no-register] [--build-id BUILD_ID]
1539                      [-i | -f | --force]
1540                      files [files ...]
1541binstar upload: error: too few arguments
1542command exited with status 2
1543Exit BINSTAR_BUILD_RESULT=error
```

**Comment by PeterDSteinberg** [comment] 2015-10-13 22:36
Earlier in the build log I noticed:
```bash
WARNING: conda-build appears to be out of date. You have version 1.17.0 but the
111latest version is 1.18.0. Run
112
113conda update -n root conda-build
```

**Comment by srossross** [comment] 2015-10-13 22:52
> Earlier in the build log I noticed

This will vary from machine to machine.

**Comment by amccarty** [comment] 2015-11-09 17:15
Having the same problem here. Upload works fine via `anaconda build submt .` however `--channel` value is missing via git push:

**git push:**

```
[Build Targets]
anaconda  -q -t $TOKEN upload --force --user amccarty --package riddle  --channel  /home/binstar/miniconda/conda-bld/linux-64/*.tar.bz2 --build-id 15.0
usage: anaconda upload [-h] [-c CHANNELS] [--no-progress] [-u USER]
                       [-p PACKAGE] [-v VERSION] [-s SUMMARY]
                       [-t PACKAGE_TYPE] [-d DESCRIPTION]
                       [--thumbnail THUMBNAIL] [--no-register]
                       [--build-id BUILD_ID] [-i | -f | --force]
                       files [files ...]
anaconda upload: error: too few arguments
command exited with status 2
Exit BINSTAR_BUILD_RESULT=error
```

**anaconda build submit .**

```
[Build Targets]
anaconda  -q -t $TOKEN upload --force --user amccarty --package riddle  --channel dev /home/binstar/miniconda/conda-bld/linux-64/*.tar.bz2 --build-id 16.0
Using anaconda-server api site http://api.anaconda.org
[WARNING] Distribution linux-64/riddle-0.0.1-py27_1.tar.bz2 already exists ... removing
Exit BINSTAR_BUILD_RESULT=success
```

**Comment by amccarty** [comment] 2015-11-09 19:06
I found that if i use `anaconda build save` to save the settings (with `--channel dev`) the CI -> Edit -> Channel field on the build page gets updated and the git push method builds and uploads to the dev channel. I think we should default to **dev** for upload as without specifying a channel the package can't (AFAIK) get uploaded anywhere. The CI options show the Channel as "optional" with  **dev** greyed out. I think we should either force that as the default or blank it out, adding a note that it's *required* if a user wants to be able to upload his/her packages.

**Comment by stephenakearns** [comment] 2015-11-10 04:12
@rafaelhbarros - I think there may be a duplicate of this somewhere - no action required, but heads-up in case you run across it.

**Comment by rafaelhbarros** [comment] 2015-11-10 15:31
I did run across it, that's the one I fixed.

**Closed** 2015-11-10 19:59 UTC
Labels: bug, Component - Build
